language: java
deploy:
  provider: releases
  api_key:
    secure: FX45AOgCR6EKqruAwU6OiL2ilfGxrA4KTqWD3xwB6jzRJ/0LsB0gkqNHSM5/cGQpR/SxNne1DRvNFo6ydNl/PdvJ/QSAVoCOylBL2OLhJ56Sf1iU+BL+OFw4xFwY9kyI2euQ09M7lxh96hOKaU+Mcu7LyDVKSCEYFKB9kXKO0BkzsnDKLoR7BUSV0tHSshBE6AA0r01F/tpqiFd12SDjZ4LzgHMjAo8ftGFidpLISsCAdtWzItln2wLFnpfnsAKQtOvWOZ1fY1VOsUiO1UCaHyvAJwZbW+2ad57dlnlbQPcIJnfAOZafe8lLsBtLaj6RmDLL6kqbG7peVcH/WoYYpMdGF5TAFk59f6h6qyH97PD5nxnBHHrGMhH7MFX8I1u62uH4YEI10E/+DVn4NvpIFUzM0AzL5zqQORBb+lYLM+18XKLEhcSwa0i6TdcmcMzXbc++nGrUShjKba4/YFAhKLhKZafTl6ZUCsRkb9nw5GCVdMl96B0YCOBKBECM7najrILob294RlZI2xLq+gc2A4+6Oy4l6C/B1ao9USon+bfpMMFMjtaNTuKOs12koq1J9tLxdMuiGhGpjSaIfLJl4uOiC9TteKZ6j0St6weh3fLey3vl5wKNrNA8jarkuCQjTA5SxkneNEvXKrV72UD7aaMkGRHSzBU4BEkeyrOtRio=
  file: target/juggl-raffle.jar
  on:
    repo: JUGGL/raffle
jdk:
  - oraclejdk8